MONGODB_HOST: mongodb.daws86s.blog
REDIS_HOST: redis.daws86s.blog
CATALOGUE_HOST: catalogue.daws86s.blog
CART_HOST: cart.daws86s.blog
USER_HOST: user.daws86s.blog
RABBITMQ_HOST: rabbitmq.daws86s.blog
MYSQL_HOST: mysql.daws86s.blog
SHIPPING_HOST: shipping.daws86s.blog
PAYMENT_HOST: payment.daws86s.blog